from pathlib import Path
r=Path(__file__).resolve().parent;w=r.parents[2]
s=(w/'.de67/work-ledger.md').read_text()
s=s.replace('Coordinator may assign GPT-6 Astra for the coupled implementation (low recommended, effort chosen by judgment), preserve current shared-file/runtime ownership, and arrange GPT-6 Luna to repeat the full native Mac playtest on the corrected build.', 'Preserve current shared-file/runtime ownership; GPT-6 Luna performs the full native Mac playtest on the corrected build. Coordinator assignment choices remain in its role-scoped owner context.')
s=s.replace('Owner coding assignment: Use GPT-6 Astra for any implementation after source-bound profiling.', 'Owner coding constraint: NPC wait/sleep implementation is assigned to GPT-6 Astra after source-bound profiling.')
s=s.replace('Use a named GPT-6 Luna assignment for the next live proof so its returned partial turn has the supported durable quiescence receipt.', 'The live proof now has a named GPT-6 Luna owner whose returned partial turn has the supported durable quiescence receipt; this is the existing assignment, not a request to add a nested operator.')
key='  - Assignment R-CAOL-FIRST-SMOKE-exploration-003:'
pos=s.index(key)
addition='''  - Review continuation, 2026-09-25 (review-smoke-002-20260925/report.md): Exploration-002's original game is saved at minute 8454 / turn 5259256 and gracefully closed, with no new whole-claim acceptance. Preserve checkpoint 17 and its saved-state limitations. The immediate game priority is the unfinished identity/physical-return repair under independent R-CAOL-DISPATCH-VISIT-exploration-001, followed by the complete Mac smoke ecology. Its seven-file draft is unverified; retain `build_logs/dispatch-visit-001/identity-route-repair/wind-down/CONTINUE.md`, exact patch/hashes and parked minute-8043 session. Do not replay setup or declare abstract timers proof of scout movement. Remaining first-light proof stays independent.
  - Assignment R-CAOL-FIRST-SMOKE-exploration-004: GPT-6 Sol repairs native quicksave-result usability for current playtest checkpoints. Reproduce the exact `not_needed` replies after waits in `review-smoke-002-20260925/harness-excerpts.json` (original transcript lines 2597, 3647, 3833) and contrast successful pause/save/collect at 7386–7421. At `src/game_io.cpp` quicksave, `src/do_turn.cpp` action/dirty tracking, the native save receipt and `tools/openclaw_harness/gameplay_display.py` presentation, make a compact result distinguish a real write, a no-op and a failed save, with the known durable saved turn or explicit uncertainty. Explain the actual no-op cause without claiming the world is current merely because the dirty-action counter is zero. Reuse existing receipt fields/control paths; preserve ordinary save semantics, failure safety and evidence identities. Do not silently advance a turn to force saving, invent a new save control or change gameplay/dirty tracking without reproducing a persistence defect. Validate unchanged repeated save, elapsed wait/no-op, real write, stale snapshot and failed write through production-path tests; use a separate Luna only if live Mac confirmation is needed. This scoped tooling work is independent of Astra's coupled ecology repair and must coordinate shared C++ files before editing. Preserve accepted lifecycle proof; this does not reopen the closed harness campaign. Return measured output/recovery comparison and remaining uncertainty, not claimed token savings.
  - Native cleanup candidate review: Exploration-003 receipt `cff05b33c17e4c90d7fdfc4b0aa80f61d0b53a5124b9ead684bb3c19cfc58e59` remains valid staged work, not an installed fix. Its CLI-exit prerequisite and absent historical PID/birth receipts cannot settle the reported original interrupted native child or an active coordinator's Q1. Do not promote or duplicate it as that remedy. Current named-owner wind-down completed with the existing reminder and preserved unfinished tasks. Reuse this review's original handles if new transport evidence changes that conclusion.
'''
s=s[:pos]+addition+s[pos:];(r/'work-ledger.candidate.md').write_text(s)
p=w/'.agents/skills/caol-harness/references/live-operation.md';raw=p.read_bytes();(r/'live-operation.before.md').write_bytes(raw)
replacements={
 b'--wait-seconds REMAINING_SECONDS collect --request-id REQUEST_ID': b'--wait-seconds REMAINING_SECONDS collect',
 b'`collect --request-id` for that exact identity; a retained latest completed result can be replayed': b'`collect` in that same session; a retained latest completed result can be replayed',
 b'action needs `collect`, never resubmission. `collect` is idempotent for the latest collected': b'action needs `collect`, never resubmission. The client selects its recorded pending request; no\nrequest-ID lookup is needed. An optional `--request-id` checks an already known identity.\n`collect` is idempotent for the latest collected'
}
for a,b in replacements.items():
 assert a in raw,a
 # Preserve surrounding source line endings.
 raw=raw.replace(a,b.replace(b'\n',b'\r\n') if b'\r\n' in raw else b)
(r/'live-operation.candidate.md').write_bytes(raw)
print('Staged exact existing collect guidance, independent save-result assignment, preserved ecology recovery')
