from pathlib import Path
import json,sys,re,sqlite3,hashlib
w=Path.cwd();o=w/'.de67/task-logs/review-signal-proof-006';p=w/'.de67/work-ledger.md'
old=(o/'work-ledger.md.before').read_text();assert p.read_text()==old
start=old.index('- [ ] R-CAOL-SIGNAL-PROOF —');end=old.index('- [ ] R-CAOL-TRAVELLING-COST —',start)
block=old[start:end]
issued=next(x for x in block.splitlines() if x.startswith('  - Assignment R-CAOL-SIGNAL-PROOF-exploration-006:'))
stage='  - Assignment R-CAOL-SIGNAL-PROOF-exploration-007: Stage an isolated installed-method candidate for the measured named-worker idle-wait overhead in `.de67/task-logs/review-signal-proof-006/idle-wait-usage.json`. This is independently useful supporting tooling, not a prerequisite to continue native gameplay or new signal acceptance. The actual delivered named_worker_contract caps each CLI wait at 60 seconds; worker_library.wait returns a full unchanged describe record and the outer functions.exec yield adds another model turn. Inspect the existing App Server mailbox/dispatcher and supervisor event ownership, then remove repeated unchanged-status model work through the smallest supported interruptible event/continuation route. Preserve owner messages, worker questions/results, cancellation, exact assignment identity, deadline wake, crash recovery, and exclusive coordinator/restart ownership. Do not solve this by blocking owner responsiveness with a long shell sleep or imposing another polling quota. Ordinary workers stage candidate files and evidence only; the exclusive mutator validates and promotes installed method changes. Reproduce unchanged-running intervals plus real message/result/deadline/error events and compare model-visible calls and total bytes against the retained trace. Run the applicable method-candidate/lifecycle tests and report capability limits, full-tree cost and any unmeasured savings. If a safe event route is unavailable, return the exact capability gap without inventing a second supervisor or changing the product outcome.'
newblock='''- [ ] R-CAOL-SIGNAL-PROOF — One native local-sound/return journey is reported proved; signal memory, original-clue support and comparable populated performance remain open.
  - DFS slices: `R-CAOL-SIGNAL-PROOF-S001`
  - Current handoff, review 2026-09-21: exploration-006 has returned from `evidence_scope_repair`; its deadline task is still open. Sol should ingest the exact returned result through the existing ownership/receipt path before new dispatch. Worker result `.de67/state/worker-library/results/9d75351eee3d4584b927f4127aa9f48e/fde4fbbc8e0c3ffe867e06beac3d701f48dbbf87c44ad600312e46fb1c41b183.md`; receipt draft `.de67/task-logs/R-CAOL-SIGNAL-PROOF-exploration-006/worker-receipt-success.json`. The draft uses narrow R-033/alternate-lineage labels: bind the durable result to the actual task and semantic-surface-cockpit lineage, preserving its scoped verdict rather than importing it as whole-claim acceptance.
'''+issued+'''
  - Returned proof: Current-source run `c79899abce5a7e064f1594ab06726c5b037fba81994d46ef12cc7b2c4c09ab0f` reports supply-empty drive 708 crossing unchanged threshold 500, local watch, native source at minute 9365 and OMT (138,52,0), and matching returned report at minute 9426. Witness `.de67/task-logs/R-CAOL-SIGNAL-PROOF-exploration-006/r033-drive500-success-witness.json` identifies J0053/J0062 and has focused scope. The worker reports 116 targeted C++ assertions, four fixture tests, source-bound build, registry rebuild and exact game/bridge exit. Preserve repaired initial NPC route binding, requested wait duration, bounded semantic receipt history and same-minute typed-observation/idempotence fixes. These are reported focused results pending ordinary coordinator ingress, not a new acceptance here.
  - Remaining outcome: Use the successful journey and current interfaces as the starting point for FS S001's still-unproved stationary source discovery/removal/bubble-edge behavior, original sound age across save/reload, and support of an original signal-origin camp clue alongside its separate returned-report lead. Preserve required native before/after and comparable populated performance/alarm boundaries; generic saved-world continuity or a returned report alone does not prove signal-memory/provenance. Choose useful journeys that share these outcomes where possible, with one owner for coupled state/fixture/interface changes, rather than a new detached harness cleanup campaign. Test demonstrated repairs through the public route the receiving journey uses; retain settled controls and rerun only affected proof. The worker's no-replay statement protects the completed local-watch/return case, not every remaining FS boundary. Sol may subdivide independent work and chooses the route and whole-claim estimate from the actual remainder.
  - Working entry points: `tools/openclaw_harness/play_cli.py` and the registry-selected `r033.phase4_semantic_autonomous_sound_return_drive500_rev1_mcw`; source-bound build owner `python3 tools/openclaw_harness/build_source_bound_macos.py --renderer tiles`. Last focused commands were `./tests/cata_test 'hostile_camp_local_structural_sound_is_persisted_before_abstract_cadence'` and `python3 tools/openclaw_harness/r033_autonomous_sound_return_fixture_test.py`. Run the FS-required nonzero selectors against the final affected revision where not already covered. The earlier root-Makefile route and all superseded 003–005 instructions/results remain retrievable in `.de67/task-logs/review-signal-proof-006/work-ledger.md.before`; they are history, not a competing current assignment.
'''+stage+'''
  - Subtasks:
    - [done] establish-autonomous-dispatch-premise :: Returned native proof reports drive 708 above unchanged threshold 500; retain the drive-358 negative control and exact fixture evidence.
    - [active] prove-sound-to-return-journey :: Ingest the focused native local-watch/return result; reconcile the separate original signal-origin clue support boundary without replaying settled proof.
    - [open] prove-signal-memory-boundaries :: Cover original age/provenance across save/reload and stationary unchanged versus removed or aged sources through native use.
    - [open] bind-populated-performance :: Retain comparable before/after advancing-turn measurements and explicit alarm or uncertainty results for the populated journey.
    - [open] reconcile-focused-controls-and-cleanup :: Reuse returned test/cleanup evidence, confirm remaining required nonzero selectors and exact identities at final source scope.
'''
new=old[:start]+newblock+old[end:]
stale=next(x for x in new.splitlines() if x.startswith('  - Returned-task continuation, owner mutation 2026-09-21: R-HARNESS-EXECUTION-exploration-003'))
replacement='  - Earlier startup recovery is superseded by the successful exploration-003 result below. Original failed-attempt context is retained in `.de67/task-logs/review-signal-proof-006/work-ledger.md.before`; the optional capture failure is not a current blocker.'
new=new.replace(stale,replacement)
p.write_text(new)
sys.path.insert(0,'/Users/josefhorvath/.codex/skills/de67/de-67-3/scripts')
from mutation_guard import validate_work_ledger
from policy_kernel import exploration_assignment
items=validate_work_ledger(p,w/'.de67/FS.md',state=w/'.de67/state/deadlines.sqlite3',lineage_id='semantic-surface-cockpit')
assert issued in new
assert old[:start].replace(stale,replacement)==new[:new.index('- [ ] R-CAOL-SIGNAL-PROOF —')]
assert old[end:]==new[new.index('- [ ] R-CAOL-TRAVELLING-COST —'):]
for name in ['FS.md','WEC.md','phase3-policy.d67']:assert (w/'.de67'/name).read_bytes()==(o/(name+'.before')).read_bytes()
a,source=exploration_assignment(new,'R-CAOL-SIGNAL-PROOF-exploration-007','R-CAOL-SIGNAL-PROOF');assert source=='task-specific ledger assignment'
assert 'remains open, with worker' in stale and 'remains open, with worker' not in replacement
c=sqlite3.connect('file:'+str(w/'.de67/state/deadlines.sqlite3')+'?mode=ro',uri=True);c.row_factory=sqlite3.Row
accept=[dict(r) for r in c.execute('select * from claim_acceptances order by lineage_id,claim_id,acceptance_number')]
(o/'accepted-before.json').write_text(json.dumps(accept,indent=2))
(o/'handoff-validation.json').write_text(json.dumps({'ledger_guard':'passed','active_claims':len(items),'accepted_rows':len(accept),'issued006_preserved':True,'other_claims_preserved_except_superseded_execution_note':True,'FS_WEC_policy_unchanged':True,'method_assignment_source':source,'method_assignment':a,'old_signal_block_bytes':len(block.encode()),'new_signal_block_bytes':len(newblock.encode()),'old_context_preserved':str(o/'work-ledger.md.before'),'limits':'No successor delivery/use or savings claimed. Returned native result remains pending normal ingress; no lifecycle task/claim status modified.'},indent=2))
print(json.dumps({'ledger_guard':'passed','accepted_rows':len(accept),'assignment_source':source,'old_signal_bytes':len(block.encode()),'new_signal_bytes':len(newblock.encode())}))
